openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jm-root/jm-log/1.0.0
info:
  version: "1.0.0"
  title: jm-log-api
  description: 日志系统API
paths:
  /log/logs/{id}:
    post:
      description: 更新日志信息
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogInfo'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetInfo'
    get:
      description: 获取日志信息
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogInfo'
components:
  schemas:
    LogInfo:
      type: object
      properties:
        data:
          type: object
      description: 日志信息
    RetInfo:
      type: object
      properties:
        ret:
          type: integer
          format: int32
          example: 1
      description: 结果信息
